import type { RawConfig } from '../model-config'

/**
 * The shapes the baked reachability dataset is written in.
 *
 * The dataset is generated by scripts/fetch-reachability.mjs from the clef-evals
 * Decision Model Leaderboard and from each model's published HuggingFace config.
 * The generated module imports these types, so the fetch script and the
 * calculators cannot disagree about the fields a record carries.
 */

/** One scored area of the Decision Index, with the share it carries. */
export interface ReachabilityArea {
  id: string
  label: string
  weight: number
}

/** Where the leaderboard numbers came from, copied so the page can cite them. */
export interface ReachabilitySource {
  /** When this repository last baked the dataset. */
  generatedUtc: string
  /** The leaderboard document the models and scores were read from. */
  leaderboardUrl: string
  /** The label of the upstream leaderboard, for example Decision Index 0.2.1. */
  upstreamLabel: string
  /** When the upstream leaderboard itself was generated. */
  upstreamGeneratedUtc: string
  /** The machine the upstream leaderboard was measured on. */
  upstreamHardware: string
  /** The upstream leaderboard URL. */
  upstreamUrl: string
  /** The number of benchmarks in the scored panel. */
  panelSize: number
  /** The scored areas, with the weight each one carries. */
  areas: ReachabilityArea[]
}

/**
 * One model on the leaderboard, reduced to the fields the reachability page
 * needs.
 *
 * The score fields are carried so the table can rank and filter on them. The
 * config is not carried here. It lives in a separate map keyed by `configKey`,
 * so several records that share one base checkpoint share one config object.
 */
export interface ReachabilityModelRecord {
  /** Stable identifier, unique within the dataset. */
  engine: string
  /** Display name. */
  name: string
  /** Publisher, or null when the leaderboard does not name one. */
  org: string | null
  /** How the checkpoint was produced, for example a LoRA or a full fine-tune. */
  kind: string
  /** The checkpoint the model was built on, or null when it is closed. */
  baseModel: string | null
  /** A link to the model card or the source repository. */
  modelUrl: string | null
  /** Parameter count, or null when the leaderboard does not list one. */
  params: number | null
  /** The Decision Index, which is the score the table ranks on. */
  index: number | null
  /** Median response latency in milliseconds, or null. */
  latencyMedian: number | null
  /** 95th percentile response latency in milliseconds, or null. */
  latencyP95: number | null
  /** True when the model is served behind a closed hosted API. */
  closed: boolean
  /** How the leaderboard row was contributed, for example community. */
  source: string | null
  /** Benchmarks the model was scored on. */
  panelCoverage: number | null
  /** Benchmark ids the model was not scored on. */
  missing: number[]
  /**
   * The dtype or quantisation the published config declares, as a display
   * hint. It is null when the config is absent or declares nothing.
   *
   * The calculator does not trust this string. It runs the full format
   * detector over the config instead. The hint only labels a record whose
   * config could not be read.
   */
  formatHint: string | null
  /** Key into the baked config map, or null when no config was available. */
  configKey: string | null
}

/** The baked configs, keyed by HuggingFace repository id. */
export type ReachabilityConfigs = Record<string, RawConfig>
